# Generated by Django 5.1.1 on 2024-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
