# Generated by Django 5.1.1 on 2024-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_client_date_of_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('economy', 'Эконом'), ('standart', 'Стандарт'), ('luxury', 'Люкс')], default='economy', max_length=255),
        ),
    ]
