# Generated by Django 5.1.1 on 2024-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_room_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creationDate',
        ),
    ]
